#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register-index:
  path: /register
  methods: GET
  controller: App\Controller\RegisterController::index

register-store:
  path: /register
  methods: POST
  controller: App\Controller\RegisterController::store

home:
  path: /home/{id}
  methods: GET
  controller: App\Controller\RecordController::index

record-store:
  path: /home/{id}
  methods: POST
  controller: App\Controller\RecordController::store

record-delete:
  path: /record/delete/{id}
  methods: POST
  controller: App\Controller\RecordController::deleteRecord

edit:
  path: /record/edit/{id}
  methods: GET
  controller: App\Controller\RecordController::edit

record-update:
  path: /record/edit/{id}
  methods: POST
  controller: App\Controller\RecordController::updateRecord

login:
  path: /login
  methods: GET
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  methods: GET

administrator-page:
  path: /administrator
  methods: GET
  controller: App\Controller\AdministratorController::index

administrator-delete:
  path: /administrator/delete/{id}
  methods: POST
  controller: App\Controller\AdministratorController::deleteUser

administrator-update:
  path: /administrator/update/{id}
  methods: POST
  controller: App\Controller\AdministratorController::updateUser



