#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register-index:
  path: /register
  methods: GET
  controller: App\Controller\RegisterController::index

register-store:
  path: /register
  methods: POST
  controller: App\Controller\RegisterController::store

home:
  path: /home/{id}
  methods: GET
  controller: App\Controller\RecordController::index